database_hostname = "localhost:3306"
database_username = "root"
database_password = "ascent"
database_name = "emucoach_v15_vip_world"

repack = "catav15"

[[manipulation]]
type = "creature_template"
column = "entry"
id = [40]
modifiers = [
    {key="name", value="Kobold MINER"},
    {key="difficulty_entry_1", value=2},
    {key="difficulty_entry_2", value=3}
]
