database_hostname = "localhost:3306"
database_username = "root"
database_password = "ascent"
database_name = "emucoach_v15_vip_world"

repack = "catav15"

[[manipulation]]
type = "creature_template"
column = "entry"
id = [40]
modifiers = [
    {key="name", value="Kobold DICKHEAD"},
    {key="difficulty_entry_1", value=1},
    {key="difficulty_entry_2", value=1}
]

[[manipulation]]
type = "scale_creature_in_zone_area"
zone_id = 11
area_id = 11
modifiers = [
    {key="Health_mod", value=0.5},
]
